// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: service_handle_db.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HandleDBClient is the client API for HandleDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandleDBClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type handleDBClient struct {
	cc grpc.ClientConnInterface
}

func NewHandleDBClient(cc grpc.ClientConnInterface) HandleDBClient {
	return &handleDBClient{cc}
}

func (c *handleDBClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.HandleDB/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handleDBClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.HandleDB/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandleDBServer is the server API for HandleDB service.
// All implementations must embed UnimplementedHandleDBServer
// for forward compatibility
type HandleDBServer interface {
	Register(context.Context, *RegisterRequest) (*UserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedHandleDBServer()
}

// UnimplementedHandleDBServer must be embedded to have forward compatible implementations.
type UnimplementedHandleDBServer struct {
}

func (UnimplementedHandleDBServer) Register(context.Context, *RegisterRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedHandleDBServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedHandleDBServer) mustEmbedUnimplementedHandleDBServer() {}

// UnsafeHandleDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandleDBServer will
// result in compilation errors.
type UnsafeHandleDBServer interface {
	mustEmbedUnimplementedHandleDBServer()
}

func RegisterHandleDBServer(s grpc.ServiceRegistrar, srv HandleDBServer) {
	s.RegisterService(&HandleDB_ServiceDesc, srv)
}

func _HandleDB_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandleDBServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandleDB/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandleDBServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandleDB_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandleDBServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HandleDB/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandleDBServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandleDB_ServiceDesc is the grpc.ServiceDesc for HandleDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandleDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HandleDB",
	HandlerType: (*HandleDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _HandleDB_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _HandleDB_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_handle_db.proto",
}
